from __future__ import annotations

from dataclasses import replace
import importlib

from fastapi.testclient import TestClient
import pytest


@pytest.fixture()
def client(tmp_path, monkeypatch):
    db_path = tmp_path / "config_forge_test.sqlite3"
    monkeypatch.setenv("CONFIG_FORGE_DB_PATH", str(db_path))

    import app.main as main_module

    importlib.reload(main_module)

    with TestClient(main_module.app) as test_client:
        yield test_client


# Generated by GitHub Copilot
def _assert_error_contract(
    response,
    expected_status: int,
    expected_code: str,
    expected_message: str | None = None,
    expect_details: bool = False,
) -> None:
    """Validate normalized FastAPI error envelope fields for contract checks."""
    assert response.status_code == expected_status
    payload = response.json()
    assert isinstance(payload.get("error"), dict)
    assert payload["error"]["code"] == expected_code
    assert isinstance(payload["error"]["message"], str)
    if expected_message is not None:
        assert payload["error"]["message"] == expected_message
    assert isinstance(payload["error"]["request_id"], str)
    assert payload["error"]["request_id"]
    if expect_details:
        assert "details" in payload["error"]


def test_create_and_validate_success(client: TestClient) -> None:
    create_response = client.post(
        "/api/v1/configs",
        json={
            "service_name": "risk-router",
            "environment": "staging",
            "provider": "openai",
            "parameters": {
                "model": "gpt-4o-mini",
                "temperature": 0.3,
                "timeout_ms": 1200,
                "max_tokens": 1024,
            },
            "policy": {
                "required_keys": ["model", "temperature", "timeout_ms"],
                "forbidden_keys": ["debug_mode"],
                "max_temperature": 0.8,
                "min_timeout_ms": 300,
                "max_timeout_ms": 5000,
            },
        },
    )
    assert create_response.status_code == 200
    config_id = create_response.json()["id"]

    validate_response = client.post(f"/api/v1/configs/{config_id}/validate")
    assert validate_response.status_code == 200
    payload = validate_response.json()
    assert payload["passed"] is True
    assert payload["issues"] == []


def test_validation_failure_for_missing_keys(client: TestClient) -> None:
    create_response = client.post(
        "/api/v1/configs",
        json={
            "service_name": "summarizer",
            "environment": "prod",
            "provider": "azure-openai",
            "parameters": {
                "model": "gpt-4.1",
                "timeout_ms": 200,
                "mock_mode": True,
            },
            "policy": {
                "required_keys": ["model", "temperature", "timeout_ms"],
                "forbidden_keys": ["debug_mode"],
                "max_temperature": 1.0,
                "min_timeout_ms": 300,
                "max_timeout_ms": 5000,
            },
        },
    )
    assert create_response.status_code == 200
    config_id = create_response.json()["id"]

    validate_response = client.post(f"/api/v1/configs/{config_id}/validate")
    assert validate_response.status_code == 200
    payload = validate_response.json()
    assert payload["passed"] is False
    assert "Missing required key: temperature" in payload["issues"]
    assert "azure-openai provider requires api_version" in payload["issues"]


def test_promote_requires_passed_validation(client: TestClient) -> None:
    create_response = client.post(
        "/api/v1/configs",
        json={
            "service_name": "classifier",
            "environment": "staging",
            "provider": "openai",
            "parameters": {
                "model": "gpt-4o-mini",
                "temperature": 0.4,
                "timeout_ms": 1500,
            },
        },
    )
    config_id = create_response.json()["id"]

    blocked = client.post(
        f"/api/v1/configs/{config_id}/promote",
        json={
            "target_environment": "staging",
            "rollout_percent": 20,
            "change_ticket": "CHG-1001",
            "approved_by": "oncall-sre",
        },
    )
    assert blocked.status_code == 409

    client.post(f"/api/v1/configs/{config_id}/validate")

    allowed = client.post(
        f"/api/v1/configs/{config_id}/promote",
        json={
            "target_environment": "production",
            "rollout_percent": 25,
            "change_ticket": "CHG-1002",
            "approved_by": "platform-lead",
        },
    )
    assert allowed.status_code == 200
    body = allowed.json()
    assert body["target_environment"] == "production"
    assert body["rollout_percent"] == 25


def test_phase1_auth_required_contract(client: TestClient, monkeypatch) -> None:
    """Require API key on protected routes and return normalized unauthorized payloads."""
    import app.main as main_module

    monkeypatch.setattr(main_module, "settings", replace(main_module.settings, api_key="phase1-secret"))

    unauthorized = client.get("/api/v1/configs")
    _assert_error_contract(
        unauthorized,
        expected_status=401,
        expected_code="unauthorized",
        expected_message="api_key_invalid",
    )

    invalid_key = client.get("/api/v1/configs", headers={"X-API-Key": "wrong"})
    _assert_error_contract(
        invalid_key,
        expected_status=401,
        expected_code="unauthorized",
        expected_message="api_key_invalid",
    )

    authorized = client.get("/api/v1/configs", headers={"X-API-Key": "phase1-secret"})
    assert authorized.status_code == 200


def test_phase1_error_contract_response(client: TestClient) -> None:
    """Return normalized not-found payload when validating an unknown config id."""
    response = client.post("/api/v1/configs/999999/validate")
    _assert_error_contract(response, expected_status=404, expected_code="not_found")
