from __future__ import annotations

from contextlib import asynccontextmanager

from fastapi import Depends, FastAPI, Header, HTTPException, Request
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from starlette.exceptions import HTTPException as StarletteHTTPException

from .config import get_settings
from .middleware import (
    HostAllowlistMiddleware,
    PayloadSizeLimitMiddleware,
    RequestContextMiddleware,
    SecurityHeadersMiddleware,
)
from .models import ConfigCreate, ConfigVersion, PromotionRequest, ReleaseRecord, ValidationResult
from .service import ConfigService
from .store import Store

settings = get_settings()
AUTH_EXEMPT_PATHS = {
    "/",
    "/health",
    "/ready",
    "/healthz",
    "/readyz",
    "/docs",
    "/openapi.json",
    "/redoc",
}


# Generated by GitHub Copilot
def _request_id_from_request(request: Request) -> str:
    """Read request correlation id from middleware state or fallback headers."""
    request_id = getattr(request.state, "request_id", None)
    if isinstance(request_id, str) and request_id:
        return request_id
    return request.headers.get("X-Request-ID", "unknown")


# Generated by GitHub Copilot
def _build_error_payload(
    request: Request,
    code: str,
    message: str,
    details: object | None = None,
) -> dict[str, object]:
    """Build normalized error payload contract for API responses."""
    payload: dict[str, object] = {
        "error": {
            "code": code,
            "message": message,
            "request_id": _request_id_from_request(request),
        }
    }
    if details is not None:
        payload["error"]["details"] = details
    return payload


# Generated by GitHub Copilot
def _status_to_error_code(status_code: int) -> str:
    """Map HTTP statuses to standardized contract codes."""
    mapping = {
        400: "bad_request",
        401: "unauthorized",
        403: "forbidden",
        404: "not_found",
        409: "conflict",
        413: "payload_too_large",
        422: "validation_error",
        429: "rate_limited",
    }
    if status_code >= 500:
        return "internal_error"
    return mapping.get(status_code, "request_failed")


# Generated by GitHub Copilot
def _require_api_key(
    request: Request,
    x_api_key: str | None = Header(default=None, alias="X-API-Key"),
) -> None:
    """Enforce optional API key auth for non-probe routes."""
    if request.method == "OPTIONS" or request.url.path in AUTH_EXEMPT_PATHS:
        return
    if not settings.api_key:
        return
    if x_api_key != settings.api_key:
        raise HTTPException(status_code=401, detail="api_key_invalid")


@asynccontextmanager
async def lifespan(app: FastAPI):
    store = Store(settings.db_path)
    app.state.service = ConfigService(store)
    yield


app = FastAPI(
    title="config-forge API",
    version="0.1.0",
    lifespan=lifespan,
    dependencies=[Depends(_require_api_key)],
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)
app.add_middleware(HostAllowlistMiddleware, allowed_hosts=settings.allowed_hosts)
app.add_middleware(PayloadSizeLimitMiddleware, max_payload_bytes=settings.max_payload_bytes)
app.add_middleware(SecurityHeadersMiddleware, enable_hsts=settings.enable_hsts)
app.add_middleware(RequestContextMiddleware)


# Generated by GitHub Copilot
@app.exception_handler(StarletteHTTPException)
@app.exception_handler(HTTPException)
async def handle_http_exception(request: Request, exc: HTTPException) -> JSONResponse:
    """Return normalized payloads for expected HTTP failures."""
    message = str(exc.detail) if exc.detail is not None else "request_failed"
    return JSONResponse(
        status_code=exc.status_code,
        content=_build_error_payload(
            request=request,
            code=_status_to_error_code(exc.status_code),
            message=message,
        ),
    )


# Generated by GitHub Copilot
@app.exception_handler(RequestValidationError)
async def handle_validation_exception(request: Request, exc: RequestValidationError) -> JSONResponse:
    """Return normalized payloads for validation failures."""
    return JSONResponse(
        status_code=422,
        content=_build_error_payload(
            request=request,
            code="validation_error",
            message="request_validation_failed",
            details=exc.errors(),
        ),
    )


# Generated by GitHub Copilot
@app.exception_handler(Exception)
async def handle_unexpected_exception(request: Request, _: Exception) -> JSONResponse:
    """Return normalized payloads for unhandled internal errors."""
    return JSONResponse(
        status_code=500,
        content=_build_error_payload(
            request=request,
            code="internal_error",
            message="internal_server_error",
        ),
    )


def get_service() -> ConfigService:
    return app.state.service


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.get("/ready")
def ready(service: ConfigService = Depends(get_service)) -> dict[str, str]:
    _ = service.list_configs()
    return {"status": "ready"}


# Generated by GitHub Copilot
@app.get("/healthz", include_in_schema=False)
def healthz() -> dict[str, str]:
    """Compatibility alias for health probes expecting /healthz."""
    return health()


# Generated by GitHub Copilot
@app.get("/readyz", include_in_schema=False)
def readyz(service: ConfigService = Depends(get_service)) -> dict[str, str]:
    """Compatibility alias for readiness probes expecting /readyz."""
    return ready(service)


@app.post("/api/v1/configs", response_model=ConfigVersion)
def create_config(payload: ConfigCreate, service: ConfigService = Depends(get_service)) -> ConfigVersion:
    return service.create_config(payload)


@app.get("/api/v1/configs", response_model=list[ConfigVersion])
def list_configs(service: ConfigService = Depends(get_service)) -> list[ConfigVersion]:
    return service.list_configs()


@app.post("/api/v1/configs/{config_id}/validate", response_model=ValidationResult)
def validate_config(config_id: int, service: ConfigService = Depends(get_service)) -> ValidationResult:
    try:
        return service.validate_config(config_id)
    except ValueError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc


@app.get("/api/v1/configs/{config_id}/validation", response_model=ValidationResult | None)
def latest_validation(config_id: int, service: ConfigService = Depends(get_service)) -> ValidationResult | None:
    return service.get_latest_validation(config_id)


@app.post("/api/v1/configs/{config_id}/promote", response_model=ReleaseRecord)
def promote_config(
    config_id: int,
    payload: PromotionRequest,
    service: ConfigService = Depends(get_service),
) -> ReleaseRecord:
    try:
        return service.promote_config(config_id, payload)
    except ValueError as exc:
        detail = str(exc)
        status_code = 404 if detail == "config not found" else 400
        raise HTTPException(status_code=status_code, detail=detail) from exc
    except PermissionError as exc:
        raise HTTPException(status_code=409, detail=str(exc)) from exc


@app.get("/api/v1/releases", response_model=list[ReleaseRecord])
def list_releases(service: ConfigService = Depends(get_service)) -> list[ReleaseRecord]:
    return service.list_releases()
